name: carbon12
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  neumorphic: ^0.4.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+2
  url_launcher: ^5.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
